name = "1bpb"
type = "javascript"
account_id = "your-account-id"
workers_dev = false
route = ""
zone_id = ""

[site]
bucket = "./build"  # Specify the directory to deploy

[build]
# Command to build your project
command = "npm run build"

# Only include _worker.js for deployment
[build.upload]
include = [
  "_worker.js"        # Include only _worker.js file
]
