name = "your-project-name"
type = "javascript"
account_id = "your-account-id"
workers_dev = false
route = ""
zone_id = ""

[site]
bucket = "./build"  # Specify the directory to deploy

[build]
# Command to build your project
command = "npm run build"

# Files to include in deployment
[build.upload]
include = [
  "_worker.js"        # Include only _worker.js file
]

# Specifies the directory where the built files are located
pages_build_output_dir = "build"
